# print("    *")
# print("   * *")
# print("  *   *")
# print(" *     *")
# print("***   ***")
# print("  *   *")
# print("  *   *")
# print("  *****")

# print("    *","\n","  * *")
# print("  *   *")
# print(" *     *")
# print("***   ***")
# print("  *   *")
# print("  *   *")
# print("  *****")

print("     *     " *2)
print("    * *    " *2)
print("   *   *   " *2)
print("  *     *  " *2)
print(" *       * " *2)
print("***     ***" *2)
print("  *     *")
print("  *     *")
print('  *     *')
print("  *     *")
print("  *******")